(function() {
    'use strict';

  angular
    .module('demo', ['semantic.ui.elements.dropdown'])
    .controller('DropdownDemoCtrl', Ctrl);

  function Ctrl() {
    this.genders = [{
      label: 'Male',
      value: 'm'
    }, {
      label: 'Female',
      value: 'f'
    }];

    this.countries = [
      { short: 'ad', full: 'Andorra' },
      { short: 'ae', full: 'United Arab Emirates' },
      { short: 'af', full: 'Afghanistan' },
      { short: 'ag', full: 'Antigua' },
      { short: 'ai', full: 'Anguilla' },
      { short: 'al', full: 'Albania' },
      { short: 'am', full: 'Armenia' },
      { short: 'an', full: 'Netherlands Antilles' },
      { short: 'ao', full: 'Angola' },
      { short: 'ar', full: 'Argentina' },
      { short: 'as', full: 'American Samoa' },
      { short: 'at', full: 'Austria' },
      { short: 'au', full: 'Australia' },
      { short: 'aw', full: 'Aruba' },
      { short: 'ax', full: 'Aland Islands' },
      { short: 'az', full: 'Azerbaijan' },
      { short: 'ba', full: 'Bosnia' },
      { short: 'bb', full: 'Barbados' },
      { short: 'bd', full: 'Bangladesh' },
      { short: 'be', full: 'Belgium' },
      { short: 'bf', full: 'Burkina Faso' },
      { short: 'bg', full: 'Bulgaria' },
      { short: 'bh', full: 'Bahrain' },
      { short: 'bi', full: 'Burundi' },
      { short: 'bj', full: 'Benin' },
      { short: 'bm', full: 'Bermuda' },
      { short: 'bn', full: 'Brunei' },
      { short: 'bo', full: 'Bolivia' },
      { short: 'br', full: 'Brazil' },
      { short: 'bs', full: 'Bahamas' },
      { short: 'bt', full: 'Bhutan' },
      { short: 'bv', full: 'Bouvet Island' },
      { short: 'bw', full: 'Botswana' },
      { short: 'by', full: 'Belarus' },
      { short: 'bz', full: 'Belize' },
      { short: 'ca', full: 'Canada' },
      { short: 'cc', full: 'Cocos Islands' },
      { short: 'cd', full: 'Congo' },
      { short: 'cf', full: 'Central African Republic' },
      { short: 'cg', full: 'Congo Brazzaville' },
      { short: 'ch', full: 'Switzerland' },
      { short: 'ci', full: 'Cote Divoire' },
      { short: 'ck', full: 'Cook Islands' },
      { short: 'cl', full: 'Chile' },
      { short: 'cm', full: 'Cameroon' },
      { short: 'cn', full: 'China' },
      { short: 'co', full: 'Colombia' },
      { short: 'cr', full: 'Costa Rica' },
      { short: 'cs', full: 'Serbia' },
      { short: 'cu', full: 'Cuba' },
      { short: 'cv', full: 'Cape Verde' },
      { short: 'cx', full: 'Christmas Island' },
      { short: 'cy', full: 'Cyprus' },
      { short: 'cz', full: 'Czech Republic' },
      { short: 'de', full: 'Germany' },
      { short: 'dj', full: 'Djibouti' },
      { short: 'dk', full: 'Denmark' },
      { short: 'dm', full: 'Dominica' },
      { short: 'do', full: 'Dominican Republic' },
      { short: 'dz', full: 'Algeria' },
      { short: 'ec', full: 'Ecuador' },
      { short: 'ee', full: 'Estonia' },
      { short: 'eg', full: 'Egypt' },
      { short: 'eh', full: 'Western Sahara' },
      { short: 'er', full: 'Eritrea' },
      { short: 'es', full: 'Spain' },
      { short: 'et', full: 'Ethiopia' },
      { short: 'eu', full: 'European Union' },
      { short: 'fi', full: 'Finland' },
      { short: 'fj', full: 'Fiji' },
      { short: 'fk', full: 'Falkland Islands' },
      { short: 'fm', full: 'Micronesia' },
      { short: 'fo', full: 'Faroe Islands' },
      { short: 'fr', full: 'France' },
      { short: 'ga', full: 'Gabon' },
      { short: 'gb', full: 'England' },
      { short: 'gd', full: 'Grenada' },
      { short: 'ge', full: 'Georgia' },
      { short: 'gf', full: 'French Guiana' },
      { short: 'gh', full: 'Ghana' },
      { short: 'gi', full: 'Gibraltar' },
      { short: 'gl', full: 'Greenland' },
      { short: 'gm', full: 'Gambia' },
      { short: 'gn', full: 'Guinea' },
      { short: 'gp', full: 'Guadeloupe' },
      { short: 'gq', full: 'Equatorial Guinea' },
      { short: 'gr', full: 'Greece' },
      { short: 'gs', full: 'Sandwich Islands' },
      { short: 'gt', full: 'Guatemala' },
      { short: 'gu', full: 'Guam' },
      { short: 'gw', full: 'Guinea-Bissau' },
      { short: 'gy', full: 'Guyana' },
      { short: 'hk', full: 'Hong Kong' },
      { short: 'hm', full: 'Heard Island' },
      { short: 'hn', full: 'Honduras' },
      { short: 'hr', full: 'Croatia' },
      { short: 'ht', full: 'Haiti' },
      { short: 'hu', full: 'Hungary' },
      { short: 'id', full: 'Indonesia' },
      { short: 'ie', full: 'Ireland' },
      { short: 'il', full: 'Israel' },
      { short: 'in', full: 'India' },
      { short: 'io', full: 'Indian Ocean Territory' },
      { short: 'iq', full: 'Iraq' },
      { short: 'ir', full: 'Iran' },
      { short: 'is', full: 'Iceland' },
      { short: 'it', full: 'Italy' },
      { short: 'jm', full: 'Jamaica' },
      { short: 'jo', full: 'Jordan' },
      { short: 'jp', full: 'Japan' },
      { short: 'ke', full: 'Kenya' },
      { short: 'kg', full: 'Kyrgyzstan' },
      { short: 'kh', full: 'Cambodia' },
      { short: 'ki', full: 'Kiribati' },
      { short: 'km', full: 'Comoros' },
      { short: 'kn', full: 'Saint Kitts and Nevis' },
      { short: 'kp', full: 'North Korea' },
      { short: 'kr', full: 'South Korea' },
      { short: 'kw', full: 'Kuwait' },
      { short: 'ky', full: 'Cayman Islands' },
      { short: 'kz', full: 'Kazakhstan' },
      { short: 'la', full: 'Laos' },
      { short: 'lb', full: 'Lebanon' },
      { short: 'lc', full: 'Saint Lucia' },
      { short: 'li', full: 'Liechtenstein' },
      { short: 'lk', full: 'Sri Lanka' },
      { short: 'lr', full: 'Liberia' },
      { short: 'ls', full: 'Lesotho' },
      { short: 'lt', full: 'Lithuania' },
      { short: 'lu', full: 'Luxembourg' },
      { short: 'lv', full: 'Latvia' },
      { short: 'ly', full: 'Libya' },
      { short: 'ma', full: 'Morocco' },
      { short: 'mc', full: 'Monaco' },
      { short: 'md', full: 'Moldova' },
      { short: 'me', full: 'Montenegro' },
      { short: 'mg', full: 'Madagascar' },
      { short: 'mh', full: 'Marshall Islands' },
      { short: 'mk', full: 'MacEdonia' },
      { short: 'ml', full: 'Mali' },
      { short: 'ar', full: 'Burma' },
      { short: 'mn', full: 'Mongolia' },
      { short: 'mo', full: 'MacAu' },
      { short: 'mp', full: 'Northern Mariana Islands' },
      { short: 'mq', full: 'Martinique' },
      { short: 'mr', full: 'Mauritania' },
      { short: 'ms', full: 'Montserrat' },
      { short: 'mt', full: 'Malta' },
      { short: 'mu', full: 'Mauritius' },
      { short: 'mv', full: 'Maldives' },
      { short: 'mw', full: 'Malawi' },
      { short: 'mx', full: 'Mexico' },
      { short: 'my', full: 'Malaysia' },
      { short: 'mz', full: 'Mozambique' },
      { short: 'na', full: 'Namibia' },
      { short: 'nc', full: 'New Caledonia' },
      { short: 'ne', full: 'Niger' },
      { short: 'nf', full: 'Norfolk Island' },
      { short: 'ng', full: 'Nigeria' },
      { short: 'ni', full: 'Nicaragua' },
      { short: 'nl', full: 'Netherlands' },
      { short: 'no', full: 'Norway' },
      { short: 'np', full: 'Nepal' },
      { short: 'nr', full: 'Nauru' },
      { short: 'nu', full: 'Niue' },
      { short: 'nz', full: 'New Zealand' },
      { short: 'om', full: 'Oman' },
      { short: 'pa', full: 'Panama' },
      { short: 'pe', full: 'Peru' },
      { short: 'pf', full: 'French Polynesia' },
      { short: 'pg', full: 'New Guinea' },
      { short: 'ph', full: 'Philippines' },
      { short: 'pk', full: 'Pakistan' },
      { short: 'pl', full: 'Poland' },
      { short: 'pm', full: 'Saint Pierre' },
      { short: 'pn', full: 'Pitcairn Islands' },
      { short: 'pr', full: 'Puerto Rico' },
      { short: 'ps', full: 'Palestine' },
      { short: 'pt', full: 'Portugal' },
      { short: 'pw', full: 'Palau' },
      { short: 'py', full: 'Paraguay' },
      { short: 'qa', full: 'Qatar' },
      { short: 're', full: 'Reunion' },
      { short: 'ro', full: 'Romania' },
      { short: 'rs', full: 'Serbia' },
      { short: 'ru', full: 'Russia' },
      { short: 'rw', full: 'Rwanda' },
      { short: 'sa', full: 'Saudi Arabia' },
      { short: 'sb', full: 'Solomon Islands' },
      { short: 'sc', full: 'Seychelles' },
      { short: 'sd', full: 'Sudan' },
      { short: 'se', full: 'Sweden' },
      { short: 'sg', full: 'Singapore' },
      { short: 'sh', full: 'Saint Helena' },
      { short: 'si', full: 'Slovenia' },
      { short: 'sj', full: 'Svalbard, I Flag Jan Mayen' },
      { short: 'sk', full: 'Slovakia' },
      { short: 'sl', full: 'Sierra Leone' },
      { short: 'sm', full: 'San Marino' },
      { short: 'sn', full: 'Senegal' },
      { short: 'so', full: 'Somalia' },
      { short: 'sr', full: 'Suriname' },
      { short: 'st', full: 'Sao Tome' },
      { short: 'sv', full: 'El Salvador' },
      { short: 'sy', full: 'Syria' },
      { short: 'sz', full: 'Swaziland' },
      { short: 'tc', full: 'Caicos Islands' },
      { short: 'td', full: 'Chad' },
      { short: 'tf', full: 'French Territories' },
      { short: 'tg', full: 'Togo' },
      { short: 'th', full: 'Thailand' },
      { short: 'tj', full: 'Tajikistan' },
      { short: 'tk', full: 'Tokelau' },
      { short: 'tl', full: 'Timorleste' },
      { short: 'tm', full: 'Turkmenistan' },
      { short: 'tn', full: 'Tunisia' },
      { short: 'to', full: 'Tonga' },
      { short: 'tr', full: 'Turkey' },
      { short: 'tt', full: 'Trinidad' },
      { short: 'tv', full: 'Tuvalu' },
      { short: 'tw', full: 'Taiwan' },
      { short: 'tz', full: 'Tanzania' },
      { short: 'ua', full: 'Ukraine' },
      { short: 'ug', full: 'Uganda' },
      { short: 'um', full: 'Us Minor Islands' },
      { short: 'us', full: 'United States' },
      { short: 'uy', full: 'Uruguay' },
      { short: 'uz', full: 'Uzbekistan' },
      { short: 'va', full: 'Vatican City' },
      { short: 'vc', full: 'Saint Vincent' },
      { short: 've', full: 'Venezuela' },
      { short: 'vg', full: 'British Virgin Islands' },
      { short: 'vi', full: 'Us Virgin Islands' },
      { short: 'vn', full: 'Vietnam' },
      { short: 'vu', full: 'Vanuatu' },
      { short: 'wf', full: 'Wallis and Futuna' },
      { short: 'ws', full: 'Samoa' },
      { short: 'ye', full: 'Yemen' },
      { short: 'yt', full: 'Mayotte' },
      { short: 'za', full: 'South Africa' },
      { short: 'zm', full: 'Zambia' },
      { short: 'zw', full: 'Zimbabwe' }
    ];

    this.languages = [
      'Arabic',
      'Chinese',
      'Danish',
      'Dutch',
      'English',
      'French',
      'German',
      'Greek',
      'Hungarian',
      'Italian',
      'Japanese',
      'Korean',
      'Lithuanian',
      'Persian',
      'Polish',
      'Portuguese',
      'Russian',
      'Spanish',
      'Swedish',
      'Turkish',
      'Vietnamese'
    ];
  }
})();
